name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # lets you trigger it manually too
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/suzanne_orido"
